//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Applabs.Marketing.Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALSEmployee
    {
        public int Employee_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Gender { get; set; }
        public string D_O_B { get; set; }
        public string Technology { get; set; }
        public string Contact_Number { get; set; }
        public string Email_Id { get; set; }
        public string SSN { get; set; }
        public string EAD { get; set; }
        public bool Is_Internal_Employee { get; set; }
    }
}
