//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Applabs.Marketing.Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALSMarketing
    {
        public int Marketing_Id { get; set; }
        public string Employee { get; set; }
        public string Marketer { get; set; }
        public string Date { get; set; }
        public string Status { get; set; }
        public List<ALSEmployee> RK { get; set; }
        public List<ALSEmployee> PRK { get; set; }
    }
}
